const PLACES = [
  {id:'yaso',name:'Yaso',sub:'El pueblo de los 100 balcones',icon:'☕',zone:1,zname:'Lima → Valle Bajo (Km 0–65)',day:'both',slot:'mañana',dur:'30–45 min',mins:40,types:['cult','food'],gem:false,reco:true,trek:null,
   maps:'https://www.google.com/maps/search/Yaso+Canta+Lima+Peru',
   desc:'Parada de desayuno en ruta directa, sin desvío. Balcones de madera del s. XIX intactos. Tamales canteños y chicharrón con camote desde las 7am.',
   hist:'Localidad del distrito de Canta. Los balcones corresponden al estilo mestizo republicano del s. XIX: técnica de quishuar y aliso andino adaptada del colonial hispano. El valle del Chillón fue eje Lima–sierra desde tiempos prehispánicos; la carretera actual sigue los caminos preincas.',
   leg:'En noches de neblina se escuchan voces en los balcones vacíos — los espíritus de los arrieros coloniales comentan el precio de la coca y el estado del camino.',
   why:'Está EN la ruta directa. Único pueblo con esta densidad de arquitectura balconera intacta entre Lima y Canta.',
   src:'Rostworowski, M. (1978). Señoríos indígenas de Lima y Canta. IEP.',
   plato:{e:'🫔',n:'Tamales canteños + chicharrón con camote',d:'Masa densa de maíz, relleno de pollo con ají panca. S/8–12.'}},

  {id:'canta',name:'Canta Centro',sub:'Ciudad colonial · fundada 1540',icon:'⛪',zone:2,zname:'Canta & Obrajillo (Km 105–108)',day:'both',slot:'mediodía',dur:'30–60 min',mins:45,types:['cult'],gem:false,reco:true,trek:null,
   maps:'https://www.google.com/maps/search/Plaza+de+Armas+Canta+Lima+Peru',
   desc:'Iglesia colonial del s. XVII, plaza con fuente original. Punto de almuerzo y reabastecimiento. Mercado dominical: queso serrano, cuy, chicha.',
   hist:'Fundada en 1540. El Virrey Toledo (1570) concentró aquí a los Atavillos de la altura. El curacazgo de Canta fue documentado por el extirpador de idolatrías Cristóbal de Albornoz por su resistencia a la evangelización.',
   leg:'El primer cura no se descompuso al morir — lo enterraron tres veces y volvía al altar. Al cuarto intento lo dejaron estar. / El río Chillón de noche no repite lo que le dices: te devuelve lo que necesitas oír.',
   why:'Única ciudad colonial en ruta con plaza e iglesia originales. Mercado dominical (solo dom): queso serrano y chicharrón de cuy frescos.',
   src:'AGN, Visitas de Toledo 1570–75.',
   plato:{e:'🐟',n:'Trucha frita + ceviche del Chillón',d:'La trucha se pesca ese día. Restaurantes frente al río. S/20–25.'}},

  {id:'obrajillo',name:'Camping Rumichaca',sub:'Base nocturna sábado · S/15 · 992353090',icon:'🏕️',zone:2,zname:'Canta & Obrajillo (Km 105–108)',day:'sat',slot:'noche',dur:'Final del sábado',mins:0,types:['camp'],gem:false,reco:true,trek:null,
   maps:'https://maps.app.goo.gl/gEbiQmph5zZjWpby8',
   desc:'Llegas aquí al final del día. Piscinas del Chillón, tobogán de piedra, zona de fogata, Intipunku. Reserva antes: 992353090.',
   hist:'"Obrajillo" = diminutivo de obraje: talleres coloniales de trabajo forzado textil (s. XVI–XVIII). Establecido el 24 de junio de 1775. Las reducciones toledanas de 1570 trasladaron aquí a los Atavillos de las alturas.',
   leg:'Duendes de sombrero rojo en el cerro en noches sin luna, guiando o extraviando hacia tesoros Atavillos. / Las "sirinus" andinas hacen olvidar el camino al hombre solo — la cura: que alguien grite su nombre tres veces.',
   why:'El cielo a 2,600 msnm sin contaminación lumínica en junio es de los mejores cerca de Lima.',
   src:'AGN, documentos coloniales s. XVI–XVIII.',
   plato:{e:'🌽',n:'Humitas del domingo',d:'Choclo fresco, dulce o salado. Puestos en Obrajillo desde las 8am del domingo.'}},

  {id:'lucle',name:'Cascada de Lucle',sub:'Domingo mañana · cerca de Obrajillo',icon:'🌊',zone:2,zname:'Canta & Obrajillo (Km 105–108)',day:'sun',slot:'mañana',dur:'1–1.5h',mins:70,types:['nat','foto'],gem:false,reco:true,trek:null,
   maps:'https://www.google.com/maps/search/Cascada+Lucle+Obrajillo+Canta+Lima',
   desc:'Cascada a minutos del camping. Pozas del Chillón para un chapuzón. Perfecta el domingo por la mañana antes de recoger la tienda.',
   hist:'Parte del sistema hídrico del Chillón. Las comunidades han usado estas pozas para riego y crianza de trucha históricamente. Las acequias prehispánicas siguen visibles en el valle.',
   leg:'Bañarse en Lucle el último día del viaje "lava" el cansancio acumulado en carretera. El agua glaciar no cura el alma, pero el choque térmico despierta.',
   why:'La cascada más accesible sin trekking cerca del camping. Ideal mientras la tienda se seca antes de empacar.',
   src:null,plato:null},

  {id:'cantamarca',name:'Cantamarca',sub:'Ciudadela Atavillos · 3,660 msnm · ingreso libre',icon:'🏛️',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sat',slot:'mañana',dur:'3–4h total',mins:200,types:['cult','hike'],gem:true,reco:true,trek:'1h subida · difícil · 3.5 mi i/v',
   maps:'https://www.google.com/maps/search/Cantamarca+zona+arqueologica+Canta+Lima+Peru',
   desc:'Capital Atavillos (1100–1450 d.C.) + 24 colcas incas superpuestas. El auto llega a la trocha, luego 1h de sendero empinado. Clasificado difícil en AllTrails.',
   hist:'Capital del curacazgo de Canta durante el Período Intermedio Tardío (~1100–1450 d.C.). Los Atavillos construían en cimas escarpadas como defensa. Hacia 1450–70 los Incas añadieron 24 colcas alineadas (rectangulares vs. las circulares Atavillos — diferencia visible). Abandonada ca. 1550 por las reducciones. Patrimonio Cultural INC Res. 051-2006.',
   leg:'El patrón de las 24 colcas es el mapa al tesoro Atavillos enterrado antes de la conquista inca. / El último curaca enterró una vasija con semillas sagradas: "para cuando el pueblo regrese." Nadie ha vuelto a sembrar allí.',
   why:'Único sitio arqueológico cerca de Lima con dos civilizaciones superpuestas visibles, sin turistas. Pero son 3–4h — no es parada rápida.',
   src:'INC Res. 051-2006 · Rostworowski (1978) · AllTrails: citadelle-de-cantamarca.',
   plato:null},

  {id:'notrk',name:'Alternativas sin trekking',sub:'Si saltas Cantamarca · mismo bloque de tiempo',icon:'🚗',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sat',slot:'mañana',dur:'Flexible',mins:90,types:['cult','nat'],gem:false,reco:false,trek:null,
   maps:null,
   desc:'① Canta colonial a fondo (45 min): plaza, iglesia, mercado — todo plano. ② Miradores desde el auto (15 min): para en ensanchamientos hacia Huaros. ③ Más tiempo en Cullhuay y lagunas sin prisa.',
   hist:null,leg:null,
   why:'Si no quieres el trekking difícil a 3,660 msnm, estas opciones llenan el bloque sin sacrificar la experiencia general.',
   src:null,plato:null},

  {id:'cullhuay',name:'Cullhuay',sub:'La puerta de las lagunas · almuerzo 4,050 msnm',icon:'🍲',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sat',slot:'mediodía',dur:'30–45 min',mins:40,types:['food','nat'],gem:false,reco:true,trek:null,
   maps:'https://www.google.com/maps/search/San+Felipe+Cullhuay+Huaros+Canta+Lima',
   desc:'Pueblo-puerta a las lagunas. Puestos comunales con caldo de cordero caliente. Come ANTES de subir a 4,800 msnm — el cuerpo lo necesita.',
   hist:'Comunidad de San Felipe de Cullhuay, 4,050 msnm, distrito de Huaros. Territorio Atavillos de altura. El pastoreo rotativo de llamas y alpacas que ves hoy es heredero de las prácticas pre-colombinas de manejo de puna.',
   leg:'Pago a la Pachamama antes de subir: chicha, coca y flores en la tierra. Práctica cotidiana real, no actuación. / La llama blanca del nevado baja a beber en las lagunas en luna llena.',
   why:'Come aquí ANTES de subir — a 4,800 msnm el cuerpo no digiere bien. El caldo de cordero caliente es el combustible para las lagunas.',
   src:'INEI (2017) · Municipalidad de Huaros.',
   plato:{e:'🍲',n:'Caldo de cordero',d:'Con papas nativas y hierbas andinas. Puestos comunales. S/10–15.'}},

  {id:'calancayo',name:'Laguna 7 Colores (Calancayo)',sub:'4,800 msnm · Cordillera de La Viuda',icon:'🎨',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sat',slot:'tarde',dur:'1–1.5h',mins:75,types:['nat','foto'],gem:false,reco:true,trek:null,
   maps:'https://maps.app.goo.gl/FxcDLgTwx9M4jnY3A',
   desc:'Turquesa, verde, azul — colores cambian con el ángulo solar. Vista directa al Nevado de La Viuda (5,140 msnm). Quédate 30–40 min para ver el cambio. 3–7°C de día.',
   hist:'Los colores son producto de minerales en suspensión (óxidos de hierro y cobre), algas microscópicas y el ángulo solar — óptica y química lacustre. El Nevado de La Viuda es el principal reservorio hídrico de la cuenca alta del Chillón. El mito de Wakón fue documentado por Pedro Villar Córdova en 1925.',
   leg:'Wakón el monstruo devoró a Pachamama y su cuerpo emergió en la cima del nevado — "La Viuda". Sus hijos Los Willcas son ancestros de los Atavillos. Cuando la laguna cambia de color en día sin nubes, Pachamama respira.',
   why:'La laguna de colores más accesible en auto cerca de Lima. Combinar con Chuchún en el mismo día es una experiencia que poca gente hace.',
   src:'Villar Córdova, P. (1925). Arqueología del departamento de Lima.',
   plato:null},

  {id:'chuchun',name:'Laguna Chuchún',sub:'4,424 msnm · reflejo del Nevado de La Viuda',icon:'🏔️',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sat',slot:'tarde',dur:'45–60 min',mins:55,types:['nat','foto'],gem:true,reco:true,trek:null,
   maps:'https://www.google.com/maps/@-11.3763,-76.4469,14z',
   desc:'El nevado se refleja en el agua en días despejados — junio suele estarlo. Más tranquila y solitaria que Calancayo. Coords: -11.3763, -76.4469.',
   hist:'Laguna en el distrito de Huaros, comunidad de San Felipe de Cullhuay, 4,424 msnm. Parte de la cuenca del Chillón. Humedal andino con fauna lacustre protegida (patos andinos, huallatas).',
   leg:'La Chuchún es "la memoria del nevado": cuando el glaciar está bien el agua es turquesa. Si está turbia sin lluvias, algo va mal en la montaña. Los comuneros la leen como indicador natural.',
   why:'Una de las mejores vistas de nevado reflejado en laguna cerca de Lima, casi sin visitantes.',
   src:'Wikipedia: Laguna Chuchún · topographic-map.com.',
   plato:null},

  {id:'pomora',name:'Cascada de Pomora "Las Mellizas"',sub:'4,000 msnm · Km 137 · visible desde carretera',icon:'🌊',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sat',slot:'tarde',dur:'30–45 min',mins:40,types:['nat','foto'],gem:false,reco:true,trek:null,
   maps:'https://maps.app.goo.gl/CrJxQjmCYr1DyiCt7',
   desc:'10 m de caída en 8 cascadas del deshielo del Nevado Colac. 4 visibles desde la carretera. Sin trekking — camina 5–10 min en llano hasta el pie.',
   hist:'Sistema hídrico del nevado Colac, afluente de La Viuda. Desemboca en el Chillón. 4,000 msnm, distrito de Huaros. "Las Mellizas" por la doble caída en época de lluvias (nov–abr). En junio: caudal menor, agua más cristalina.',
   leg:'Quien recibe el agua de Las Mellizas tiene garantizado concebir mellizos. Mujeres hacen peregrinaciones con este propósito en agosto.',
   why:'Única cascada de altura sin trekking en la ruta — está de paso entre lagunas y el regreso al camping.',
   src:'Agencia Andina (2014) · MINCETUR Ficha N° 1851.',
   plato:null},

  {id:'puyas',name:'Puyas de Raimondi — Jarapampa',sub:'⚠️ 2h senderismo desde Huaros · 4,000 msnm',icon:'🌵',zone:3,zname:'Montaña Alta (3,660–4,800 msnm)',day:'sun',slot:'mañana',dur:'4–5h total',mins:240,types:['nat','foto'],gem:true,reco:false,trek:'8 km · 2h cada tramo desde Huaros',
   maps:'https://www.google.com/maps/search/Puyas+Raimondi+Jarapampa+Huaros+Canta+Lima+Peru',
   desc:'~1,000 plantas en 15 ha. La planta con la inflorescencia más grande del mundo (10 m). Colonia poco visitada. Nota: el lugar se llama Jarapampa, no Jaramajón. Requiere 2h de sendero desde Huaros.',
   hist:'La Puya raimondii fue descrita por el naturalista Antonio Raimondi en 1874. Vive hasta 100 años, florece UNA vez produciendo hasta 8,000 flores en tallo de 10 m, y muere. El rodal de Jarapampa (Huaros, Canta) tiene ~1,000 plantas en 15 ha a 4,000 msnm.',
   leg:'La Puya solo florece cuando alguien del pueblo muere — el tallo gigante es el alma del difunto subiendo al cielo. Cuando ves una Puya florida, bajas la voz.',
   why:'De las pocas colonias de Puyas accesibles cerca de Lima. Pero son 2h de senderismo cada tramo desde Huaros — no la hagas si el domingo tienes prisa de llegar a Lima.',
   src:'Rumbos del Perú (2017). "Canta: el insospechado bosque de puyas de Raimondi de Jarapampa."',
   plato:null},

  {id:'smash',name:"Smash N' Go",sub:'Lima · meta del domingo · almuerzo de remate',icon:'🍔',zone:4,zname:'Regreso a Lima',day:'sun',slot:'tarde',dur:'Meta del domingo',mins:60,types:['food'],gem:false,reco:true,trek:null,
   maps:'https://maps.app.goo.gl/fxCkSBshexirmhSK7',
   desc:'Tu destino final. Sale de Canta a las 11–12, llegas a Lima 1:30–2:30pm. El remate perfecto.',
   hist:null,leg:null,why:'Porque después de 2 días de trucha andina, altura y fogata, mereces un smash burger.',
   src:null,plato:{e:'🍔',n:'Smash Burger',d:'El remate del road trip. Pídelo doble.'}}
];

const TYPE_LABELS = {nat:'Naturaleza',cult:'Cultura',food:'Comida',foto:'Foto',hike:'Trekking',camp:'Camping'};
const SLOT_ORDER  = {mañana:0,mediodía:1,tarde:2,noche:3};
const ZONE_DIST   = {1:'0–65 km · hasta 1h 45min',2:'Km 105–108 · 2,600–2,750 msnm',3:'3,660–4,800 msnm · llevar abrigo',4:'~2h 30min de regreso'};
